# Generated by Django 5.0.6 on 2026-06-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('tipo', models.CharField(choices=[('delivery', 'Domicilio'), ('pickup', 'Recoger en sede')], default='delivery', max_length=12, verbose_name='Tipo de pedido')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('items', models.JSONField(default=list, verbose_name='Artículos')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='Subtotal (COP)')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('aceptado', 'Aceptado'), ('despachado', 'Despachado'), ('cancelado', 'Cancelado')], default='nuevo', max_length=12, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-creado'],
            },
        ),
    ]
