# Generated by Django 5.2.15 on 2026-07-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_wompi_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.pedido',),
        ),
    ]
